### ISSUE TITLE
IAssemblyFixture issue. Tests execution does not end. 

### ISSUE THREAD

**Issue by dmitry-kosar** [Deffiss/testenvironment-docker#55]
I’m having an issue when using IAssemblyFixture(from https://www.nuget.org/packages/Xunit.Extensions.AssemblyFixture) for EnvironmentFixture.
I works fine on my local machine, but not on CI pipeline. It does not throw any error it just runs and does not end. 

Also IClassFixture works fine, but I want to share environment between several tests. 

Here is GitHub action

```yaml
runs-on: ubuntu-latest
timeout-minutes: 5

steps:
- uses: actions/checkout@v2.3.4

- name: Setup .NET Core 5.0.x
  uses: actions/setup-dotnet@v1.8.1
  with:
    dotnet-version: 5.0.x

- name: Restore dependencies
  run: dotnet restore

- name: Build
  run: dotnet build --configuration Debug --no-restore

- name: Test
  run: dotnet test --configuration Debug --no-build --verbosity normal
```

Usage
```csharp
public class MyTests : IAssemblyFixture<EnvironmentFixture>
{
    private readonly EnvironmentFixture _environmentFixture;

    public MyTests(EnvironmentFixture environmentFixture)
    {
        _environmentFixture = environmentFixture;
    }
….
```

EnveronmentFixture
```csharp
public class EnvironmentFixture : IAsyncLifetime, IDisposable
{
    private readonly string _environmentName;
    private DockerEnvironment _environment;
    private IHost _host;

    public HttpClient TestClient { get; private set; }

    public EnvironmentFixture()
    {
        _environmentName = "test";
        Task.WaitAll(InitializeAsync());
    }

    public async Task InitializeAsync()
    {
        // Docker environment setup.
        _environment = CreateTestEnvironmentBuilder().Build();
        await _environment.Up();

        // API Test host setup
        _host = await CreateHostBuilder().StartAsync();

        TestClient = _host.GetTestClient();

        await OnInitialized(_environment.GetContainer<MongoContainer>("mongo"));
    }

```
I have mongo, redis and kafka containers registering following way

```csharp
builder.AddContainer(name, "redis", "6-alpine");
builder.AddContainer(name, "docker.io/bitnami/kafka", "2-debian-10”);
builder.AddMongoContainer("mongo”);
```
